name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2


    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
         gradle-version: "6.3" # Quotes required to prevent YAML converting to number

    - name: Generate Gradle Wrapper
      run: gradle wrapper
      
    - name: Build project
      run: ./gradlew clean build

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context:
       push: true
       tags: kevinkho/sql-proxy:latest
